# Generated by Django 5.0.4 on 2024-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False, verbose_name='Resultado ID')),
                ('calificacion', models.IntegerField(max_length=3, verbose_name='Calificaci´pn Final')),
                ('jurado', models.CharField(max_length=50, verbose_name='Jurado Calificador')),
                ('grado', models.CharField(max_length=25, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=2, verbose_name='Sección')),
                ('categoria', models.CharField(max_length=75, verbose_name='Categoria')),
            ],
        ),
    ]
