# Generated by Django 5.0.4 on 2024-05-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorResultados', '0002_alter_resultado_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baile',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False, verbose_name='Resultado ID')),
                ('jurado', models.CharField(max_length=50, verbose_name='Jurado Calificador')),
                ('grado', models.CharField(max_length=25, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=2, verbose_name='Sección')),
                ('criterio_1', models.IntegerField(verbose_name='Crit 01')),
                ('criterio_2', models.IntegerField(verbose_name='Crit 02')),
                ('criterio_3', models.IntegerField(verbose_name='Crit 03')),
                ('criterio_4', models.IntegerField(verbose_name='Crit 04')),
                ('calificacion', models.IntegerField(verbose_name='Calificación Final')),
            ],
        ),
        migrations.CreateModel(
            name='Barras',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False, verbose_name='Resultado ID')),
                ('jurado', models.CharField(max_length=50, verbose_name='Jurado Calificador')),
                ('grado', models.CharField(max_length=25, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=2, verbose_name='Sección')),
                ('criterio_1', models.IntegerField(verbose_name='Crit 01')),
                ('criterio_2', models.IntegerField(verbose_name='Crit 02')),
                ('criterio_3', models.IntegerField(verbose_name='Crit 03')),
                ('criterio_4', models.IntegerField(verbose_name='Crit 04')),
                ('criterio_5', models.IntegerField(verbose_name='Crit 05')),
                ('criterio_6', models.IntegerField(verbose_name='Crit 06')),
                ('criterio_7', models.IntegerField(verbose_name='Crit 07')),
                ('calificacion', models.IntegerField(verbose_name='Calificación Final')),
            ],
        ),
        migrations.CreateModel(
            name='Canto',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False, verbose_name='Resultado ID')),
                ('jurado', models.CharField(max_length=50, verbose_name='Jurado Calificador')),
                ('grado', models.CharField(max_length=25, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=2, verbose_name='Sección')),
                ('criterio_1', models.IntegerField(verbose_name='Crit 01')),
                ('criterio_2', models.IntegerField(verbose_name='Crit 02')),
                ('criterio_3', models.IntegerField(verbose_name='Crit 03')),
                ('criterio_4', models.IntegerField(verbose_name='Crit 04')),
                ('calificacion', models.IntegerField(verbose_name='Calificación Final')),
            ],
        ),
        migrations.CreateModel(
            name='Conocimientos',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False, verbose_name='Resultado ID')),
                ('grado', models.CharField(max_length=25, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=2, verbose_name='Sección')),
                ('calificacion', models.IntegerField(verbose_name='Calificación Final')),
            ],
        ),
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False, verbose_name='Resultado ID')),
                ('grado', models.CharField(max_length=25, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=2, verbose_name='Sección')),
                ('criterio_1', models.IntegerField(verbose_name='Juego 01')),
                ('criterio_2', models.IntegerField(verbose_name='Juego 02')),
                ('criterio_3', models.IntegerField(verbose_name='Juego 03')),
                ('criterio_4', models.IntegerField(verbose_name='Juego 04')),
                ('criterio_5', models.IntegerField(verbose_name='Juego 05')),
                ('calificacion', models.IntegerField(verbose_name='Calificación Final')),
            ],
        ),
        migrations.CreateModel(
            name='PlayBack',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False, verbose_name='Resultado ID')),
                ('jurado', models.CharField(max_length=50, verbose_name='Jurado Calificador')),
                ('grado', models.CharField(max_length=25, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=2, verbose_name='Sección')),
                ('criterio_1', models.IntegerField(verbose_name='Crit 01')),
                ('criterio_2', models.IntegerField(verbose_name='Crit 02')),
                ('criterio_3', models.IntegerField(verbose_name='Crit 03')),
                ('criterio_4', models.IntegerField(verbose_name='Crit 04')),
                ('criterio_5', models.IntegerField(verbose_name='Crit 05')),
                ('criterio_6', models.IntegerField(verbose_name='Crit 06')),
                ('calificacion', models.IntegerField(verbose_name='Calificación Final')),
            ],
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
